CREATE TABLE CQ_DI.DEV_ENV_APPL 
   (	ID NUMBER, 
	ENVIRONMENT_NAME VARCHAR2(20 BYTE) NOT NULL, 
	APPLICATION_NAME VARCHAR2(50 BYTE) NOT NULL, 
	 PRIMARY KEY (ID));

CREATE UNIQUE INDEX CQ_DI.DEV_ENV_APP_NAME_IDX ON CQ_DI.DEV_ENV_APPL (ENVIRONMENT_NAME, APPLICATION_NAME);

CREATE SEQUENCE  CQ_DI.DEV_ENV_APPL_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CQ_DI.DEV_ENV_APPL_TRG 
BEFORE INSERT ON DEV_ENV_APPL
FOR EACH ROW
   BEGIN
     SELECT DEV_ENV_APPL_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END;
////////////////////////////////////////////////////////////////////////////////////
CREATE TABLE CQ_DI.DEV1_CONFIG_DATA 
   (	ID NUMBER, 
	APPLICATION_NAME VARCHAR2(50 BYTE) NOT NULL, 
	SUB_APPLICATION_NAME VARCHAR2(50 BYTE), 
	SOURCE_APPLICATION VARCHAR2(50 BYTE), 
	TARGET_APPLICATION VARCHAR2(50 BYTE), 
	APPL_SERVICE_NAME VARCHAR2(100 BYTE) NOT NULL, 
	APPL_SERVICE_TYPE VARCHAR2(20 BYTE) NOT NULL, 
	APPL_SERVICE_STATUS VARCHAR2(15 BYTE) NOT NULL, 
	APPL_SERVICE_STATUS_INFO VARCHAR2(4000 BYTE), 
	APPL_CONFIGURATION_URL VARCHAR2(1000 BYTE), 
	APPL_CREDS_BASE64 VARCHAR2(150 BYTE), 
	APPL_PACKAGE_NAME VARCHAR2(50 BYTE) NOT NULL, 
	INFO_ENTRYDATE DATE NOT NULL, 
	APPL_DOWNTIME_ENTRY NUMBER DEFAULT 0, 
	APPL_DOWNTIME_STARTDATE DATE, 
	APPL_DOWNTIME_ENDDATE DATE, 
	APPL_SERVICE_CONF_LASTCHANGED DATE, 
	PRIMARY KEY (ID),
	CONSTRAINT CHK_DEV1_APPL_SERVICE_STATUS CHECK (APPL_SERVICE_STATUS IN ('NORMAL','HIGH','CRITICAL')),
	CONSTRAINT CHK_DEV1_APPL_SERVICE_TYPE CHECK (APPL_SERVICE_TYPE IN ('Processes','GUIServices','WebServices')));
	
CREATE UNIQUE INDEX CQ_DI.DEV1_CONFIG_DATA_IDX ON CQ_DI.DEV1_CONFIG_DATA (APPLICATION_NAME, SUB_APPLICATION_NAME, APPL_SERVICE_NAME, APPL_SERVICE_TYPE, APPL_CONFIGURATION_URL);

CREATE SEQUENCE  CQ_DI.DEV1_CONFIG_DATA_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CQ_DI.DEV1_CONFIG_DATA_TRG 
BEFORE INSERT ON DEV1_CONFIG_DATA
FOR EACH ROW
   BEGIN
     SELECT DEV1_CONFIG_DATA_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END;
   
////////////////////////////////////////////////////////////////////////////////////////////////
CREATE TABLE CQ_DI.DEV1_DB_CONFIG_DATA 
   (	ID NUMBER, 
	APPLICATION_NAME VARCHAR2(50 BYTE) NOT NULL, 
	APPL_DATABASE_NAME VARCHAR2(20 BYTE) NOT NULL, 
	APPL_SERVICE_NAME VARCHAR2(100 BYTE) NOT NULL, 
	APPL_SERVICE_TYPE VARCHAR2(20 BYTE) NOT NULL, 
	APPL_SERVICE_STATUS VARCHAR2(15 BYTE) NOT NULL, 
	APPL_SERVICE_STATUS_INFO VARCHAR2(4000 BYTE), 
	APPL_DB_SERVICE_DETAILS VARCHAR2(80 BYTE) NOT NULL,
	APPL_DB_PACKAGE_NAME VARCHAR2(50 BYTE) NOT NULL, 
	INFO_ENTRYDATE DATE NOT NULL, 
	APPL_DOWNTIME_ENTRY NUMBER DEFAULT 0, 
	APPL_DOWNTIME_STARTDATE DATE, 
	APPL_DOWNTIME_ENDDATE DATE, 
	APPL_SERVICE_CONF_LASTCHANGED DATE, 
	 PRIMARY KEY (ID),
	 CONSTRAINT CHK_DEV1DB_APPL_SERVICE_STATUS CHECK (APPL_SERVICE_STATUS IN ('NORMAL','HIGH','CRITICAL')),
	 CONSTRAINT CHK_DEV1DB_APPL_SERVICE_TYPE CHECK (APPL_SERVICE_TYPE IN ('DB','GG')));
	 
CREATE UNIQUE INDEX CQ_DI.DEV1_DB_CONFIG_DATA_IDX ON CQ_DI.DEV1_DB_CONFIG_DATA (APPLICATION_NAME, APPL_DATABASE_NAME, APPL_SERVICE_NAME, APPL_SERVICE_TYPE, APPL_DB_SERVICE_DETAILS, APPL_DB_PACKAGE_NAME);

CREATE SEQUENCE  CQ_DI.DEV1_DB_CONFIG_DATA_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CQ_DI.DEV1_DB_CONFIG_DATA_TRG 
BEFORE INSERT ON DEV1_DB_CONFIG_DATA
FOR EACH ROW
   BEGIN
     SELECT DEV1_DB_CONFIG_DATA_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END;
   
/////////////////////////////////////////////////////////////////////////////////////////////
CREATE TABLE CQ_DI.DEV2_CONFIG_DATA 
   (	ID NUMBER, 
	APPLICATION_NAME VARCHAR2(50 BYTE) NOT NULL, 
	SUB_APPLICATION_NAME VARCHAR2(50 BYTE), 
	SOURCE_APPLICATION VARCHAR2(50 BYTE), 
	TARGET_APPLICATION VARCHAR2(50 BYTE), 
	APPL_SERVICE_NAME VARCHAR2(100 BYTE) NOT NULL, 
	APPL_SERVICE_TYPE VARCHAR2(20 BYTE) NOT NULL, 
	APPL_SERVICE_STATUS VARCHAR2(15 BYTE) NOT NULL, 
	APPL_SERVICE_STATUS_INFO VARCHAR2(4000 BYTE), 
	APPL_CONFIGURATION_URL VARCHAR2(1000 BYTE), 
	APPL_CREDS_BASE64 VARCHAR2(150 BYTE), 
	APPL_PACKAGE_NAME VARCHAR2(50 BYTE) NOT NULL, 
	INFO_ENTRYDATE DATE NOT NULL, 
	APPL_DOWNTIME_ENTRY NUMBER DEFAULT 0, 
	APPL_DOWNTIME_STARTDATE DATE, 
	APPL_DOWNTIME_ENDDATE DATE, 
	APPL_SERVICE_CONF_LASTCHANGED DATE, 
	 PRIMARY KEY (ID),
	 CONSTRAINT CHK_DEV2_APPL_SERVICE_STATUS CHECK (APPL_SERVICE_STATUS IN ('NORMAL','HIGH','CRITICAL')),
	 CONSTRAINT CHK_DEV2_APPL_SERVICE_TYPE CHECK (APPL_SERVICE_TYPE IN ('Processes','GUIServices','WebServices')));
	 
CREATE UNIQUE INDEX CQ_DI.DEV2_CONFIG_DATA_IDX ON CQ_DI.DEV2_CONFIG_DATA (APPLICATION_NAME, SUB_APPLICATION_NAME, APPL_SERVICE_NAME, APPL_SERVICE_TYPE, APPL_CONFIGURATION_URL);

CREATE SEQUENCE  CQ_DI.DEV2_CONFIG_DATA_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CQ_DI.DEV2_CONFIG_DATA_TRG 
BEFORE INSERT ON DEV2_CONFIG_DATA
FOR EACH ROW
   BEGIN
     SELECT DEV2_CONFIG_DATA_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END
   
/////////////////////////////////////////////////////////////////////
CREATE TABLE CQ_DI.DEV2_DB_CONFIG_DATA 
   (	ID NUMBER, 
	APPLICATION_NAME VARCHAR2(50 BYTE) NOT NULL, 
	APPL_DATABASE_NAME VARCHAR2(20 BYTE) NOT NULL, 
	APPL_SERVICE_NAME VARCHAR2(100 BYTE) NOT NULL, 
	APPL_SERVICE_TYPE VARCHAR2(20 BYTE) NOT NULL, 
	APPL_SERVICE_STATUS VARCHAR2(15 BYTE) NOT NULL, 
	APPL_SERVICE_STATUS_INFO VARCHAR2(4000 BYTE), 
	APPL_DB_SERVICE_DETAILS VARCHAR2(80 BYTE) NOT NULL, 
	APPL_DB_PACKAGE_NAME VARCHAR2(50 BYTE) NOT NULL, 
	INFO_ENTRYDATE DATE NOT NULL, 
	APPL_DOWNTIME_ENTRY NUMBER DEFAULT 0, 
	APPL_DOWNTIME_STARTDATE DATE, 
	APPL_DOWNTIME_ENDDATE DATE, 
	APPL_SERVICE_CONF_LASTCHANGED DATE, 
	 PRIMARY KEY (ID),
	 CONSTRAINT CHK_DEV2DB_APPL_SERVICE_STATUS CHECK (APPL_SERVICE_STATUS IN ('NORMAL','HIGH','CRITICAL')),
	 CONSTRAINT CHK_DEV2DB_APPL_SERVICE_TYPE CHECK (APPL_SERVICE_TYPE IN ('DB','GG')));
	 
CREATE UNIQUE INDEX CQ_DI.DEV2_DB_CONFIG_DATA_IDX ON CQ_DI.DEV2_DB_CONFIG_DATA (APPLICATION_NAME, APPL_DATABASE_NAME, APPL_SERVICE_NAME, APPL_SERVICE_TYPE, APPL_DB_SERVICE_DETAILS, APPL_DB_PACKAGE_NAME);

CREATE SEQUENCE  CQ_DI.DEV2_DB_CONFIG_DATA_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CQ_DI.DEV2_DB_CONFIG_DATA_TRG 
BEFORE INSERT ON DEV2_DB_CONFIG_DATA
FOR EACH ROW
   BEGIN
     SELECT DEV2_DB_CONFIG_DATA_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END;
	 